# Generated by Django 5.1.1 on 2024-09-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_labtestresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='clock_number',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='LabTestResult',
        ),
    ]
