# Generated by Django 5.1.1 on 2024-09-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_alter_patientrecord_clock_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='clock_number',
            field=models.CharField(max_length=100),
        ),
    ]
