# Generated by Django 5.1.1 on 2024-09-18 06:38

import doctors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_patientrecord_clock_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='unique_code',
            field=models.CharField(max_length=12, unique=True, default=''),
        ),
    ]