# Generated by Django 5.1.1 on 2024-09-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_patientrecord_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='date_symptoms_aware',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='previous_complaints',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='previous_complaints_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='treatment_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
