# Generated by Django 5.1.1 on 2024-09-24 09:31

import doctors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_patientrecord_date_symptoms_aware_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_code', models.CharField(default=doctors.models.generate_unique_code, max_length=12, unique=True)),
                ('clock_number', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('test_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('prescription', models.TextField(blank=True, null=True)),
                ('test_result', models.TextField(blank=True, null=True)),
                ('date_symptoms_aware', models.DateField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('previous_complaints', models.BooleanField(default=False)),
                ('previous_complaints_date', models.DateField(blank=True, null=True)),
                ('treatment_description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
