# Generated by Django 5.1.1 on 2024-09-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_delete_patient_alter_patientrecord_clock_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='clock_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
