# Generated by Django 5.1.1 on 2024-10-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_alter_patientrecord_clock_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='clock_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
