# Generated by Django 5.1.1 on 2024-10-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_alter_patientrecord_clock_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='age',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='chief_complaints',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='examination',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='medical_history',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='medical_remarks',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='vitals',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
