# Generated by Django 5.1.1 on 2024-10-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_patientrecord_age_patientrecord_chief_complaints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='history_of_presenting_illness',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='chief_complaints',
            field=models.TextField(blank=True, max_length=0, null=True),
        ),
    ]
