# Generated by Django 5.1.1 on 2024-10-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0016_patientrecord_history_of_presenting_illness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='chief_complaints',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
