# Generated by Django 5.1.1 on 2024-10-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0017_alter_patientrecord_chief_complaints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
